#!/usr/bin/env sh

set -eu

repository_root=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
output_file="$repository_root/engine/build-info.generated.js"

branch=$(
    git -C "$repository_root" symbolic-ref --short HEAD 2>/dev/null ||
    printf 'detached'
)
commit=$(git -C "$repository_root" rev-parse --short HEAD)
build_date=$(date -u "+%Y-%m-%dT%H:%M:%SZ")
branch=$(printf '%s' "$branch" | sed 's/\\/\\\\/g; s/"/\\"/g')

cat > "$output_file" <<EOF
/* This file is generated by generate-build-info.sh. */

"use strict";

export const BuildInfo = Object.freeze(
    {
        branch: "$branch",
        commit: "$commit",
        date: "$build_date"
    }
);
EOF

printf 'Generated %s\n' "$output_file"
