#!/bin/sh

set -eu

repository_root=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
cd "$repository_root"

branch=$(git symbolic-ref --quiet --short HEAD 2>/dev/null || true)

if [ -z "$branch" ]
then
    branch=${GITHUB_HEAD_REF:-${GITHUB_REF_NAME:-development}}
fi

commit=$(git rev-parse --short=8 HEAD 2>/dev/null || printf 'local')
build_date=$(date -u +%Y-%m-%dT%H:%M:%SZ)

escape_json()
{
    printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

cat > engine/build-info.generated.js <<EOF_BUILD
/* Generated by generate-build-info.sh. */
globalThis.FAULKERVERSE_BUILD = Object.freeze({
    branch: "$(escape_json "$branch")",
    commit: "$(escape_json "$commit")",
    date: "$(escape_json "$build_date")"
});
EOF_BUILD

printf 'Generated build metadata for %s at %s.\n' "$commit" "$build_date"
