import {AVATAR_CHOICES,CART_CHOICES,selectPlayerChoice} from '../world/PlayerChoices.js';
export function choosePlayer()
{
    return new Promise(resolve=>{
        const root=document.createElement('section');root.id='startChoices';root.setAttribute('role','dialog');root.setAttribute('aria-label','Choose your player and cart');
        root.innerHTML='<div class="choiceCard"><h1>Your city. Your ride.</h1><p>Choose an avatar and a starting cart. Earn money from passenger fares and cash finds; spend it on fuel, food and drinks.</p><label>Avatar <select id="avatarChoice"></select></label><div class="avatarPreview" aria-hidden="true"><svg viewBox="0 0 100 150" width="80" height="110"><path class="avatarPants" d="M29 90h42l-4 49H53l-3-34-3 34H33z"/><path class="avatarSkin" d="M29 52 17 94l10 3 15-41m29-4 12 42-10 3-15-41"/><path class="avatarShirt" d="M30 49h40l7 25-9 3v21H32V77l-9-3z"/><ellipse class="avatarSkin" cx="50" cy="30" rx="17" ry="22"/><path class="avatarHair" d="M33 29V15q17-21 34 0v14l-9-14-16 6z"/><path fill="#e7e8dd" d="M31 134h17v10H27v-5zm21 0h17l4 5v5H52z"/></svg></div><label>Golf cart <select id="cartChoice"></select></label><div class="cartPreview" aria-hidden="true"><svg viewBox="0 0 180 100" width="150" height="90"><path class="cartPaint" d="M16 9h139v8H16zM13 58h144l9 22H13z"/><path stroke="#d5e4e3" stroke-width="4" d="M29 17v41m112-41v41"/><path fill="#bca782" d="M53 45h30v14H53zm41 0h30v14H94z"/><path fill="#799da7" d="m140 23 10 30h-12z"/><circle cx="38" cy="81" r="13" fill="#17232a"/><circle cx="135" cy="81" r="13" fill="#17232a"/><circle cx="38" cy="81" r="6" fill="#a8babe"/><circle cx="135" cy="81" r="6" fill="#a8babe"/></svg></div><p class="cartStats"></p><label>City activity <select id="populationChoice"><option value="busy">Busy · more cars and people</option><option value="calm">Calmer · lighter on your device</option></select></label><button type="button" id="startCity">Enter the city</button></div>';
        const a=root.querySelector('#avatarChoice'),c=root.querySelector('#cartChoice'),density=root.querySelector('#populationChoice');
        for(const [select,items] of [[a,AVATAR_CHOICES],[c,CART_CHOICES]])for(const item of items){const o=document.createElement('option');o.value=item.id;o.textContent=item.name;select.appendChild(o);}
        try{const saved=JSON.parse(localStorage.getItem('faulkerverseChoices')||'null');if(saved){a.value=String(saved.avatar);c.value=String(saved.cart);density.value=saved.population;}}catch{}
        if(!a.value)a.value='0';if(!c.value)c.value='0';if(!density.value)density.value='busy';
        const draw=()=>{const avatar=AVATAR_CHOICES[Number(a.value)],cart=CART_CHOICES[Number(c.value)];for(const [cls,color] of [['avatarShirt',avatar.shirt],['avatarSkin',avatar.skin],['avatarHair',avatar.hair],['avatarPants',avatar.pants],['cartPaint',cart.color]])root.querySelectorAll('.'+cls).forEach(el=>el.setAttribute('fill',color));root.querySelector('.cartStats').textContent=`${cart.feature} · speed ${cart.speed} · acceleration ${cart.acceleration} · brakes ${cart.braking} · ${cart.tank} L tank`;};a.onchange=c.onchange=draw;draw();
        root.querySelector('button').onclick=()=>{selectPlayerChoice(a.value,c.value,density.value);try{localStorage.setItem('faulkerverseChoices',JSON.stringify({avatar:Number(a.value),cart:Number(c.value),population:density.value}));}catch{}root.remove();resolve();};document.body.appendChild(root);root.querySelector('select').focus();
    });
}
